apiVersion: v1
kind: Service
metadata:
  name: notion-jira-automation
  labels:
    app: notion-jira-automation
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3003
      protocol: TCP
      name: http
  selector:
    app: notion-jira-automation
